[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[rpc_endpoints]
celo_sepolia = "${CELO_SEPOLIA_RPC}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
